### ISSUE TITLE
Property Id not found on SPMKContract

### ISSUE THREAD

**Issue by deryrahman** [Ditlog-Dev/ditlog-webservice#13]
@rayandrews please check primary id for this table. I didn't know, why it couldn't detect the key id

**Comment by deryrahman** [comment]
on branch features/I7-view-contract

**Comment by rayandrew** [comment]
okay will look it later this day

**Comment by rayandrew** [comment]
by using query : 

```
select * from all_tab_cols where owner = 'SILOG' and TABLE_NAME='V_SPMK_ANDROID';
```

I found that one column is __not nullable__, I think that ID_SPMK is the primary key

<img width="1411" alt="screen shot 2018-03-18 at 12 32 32" src="https://user-images.githubusercontent.com/4437323/37562986-97c884a4-2aa8-11e8-9c7c-309f4b7b6ca7.png">

@deryrahman

**Comment by deryrahman** [comment]
have you tried call ``GET /contracts``? it shows, if I'm not mistaken, ``property id not found, perhaps 'nik'``
@rayandrews

**Comment by rayandrew** [comment]
ah i found the bug

<img width="621" alt="screen shot 2018-03-18 at 19 15 37" src="https://user-images.githubusercontent.com/4437323/37565725-c782325c-2ae0-11e8-9f61-64c36112abdd.png">

`@RequestParam(value = "sort", defaultValue = "id") String sort` 
should be 
`@RequestParam(value = "sort", defaultValue = "idSPMK") String sort`

but it will generate other bug. 
if you see in the console, exception will say
`java.sql.SQLException: Fail to convert to internal representation`

and in web will say:
`JpaSystemException : could not execute query; nested exception is org.hibernate.exception.GenericJDBCException: could not execute query`

@deryrahman

**Comment by rayandrew** [comment]
i have already pushed the fixes, but still cannot see the content even http status is already 200

link : 
https://github.com/Ditlog-Dev/ditlog-webservice/commit/7904c66351c09647323b31e21fc6ef8602ee2f06

<img width="1440" alt="screen shot 2018-03-18 at 19 40 17" src="https://user-images.githubusercontent.com/4437323/37565897-43a8cbc2-2ae4-11e8-8e55-d3b29222b4c2.png">

@deryrahman

**Comment by deryrahman** [comment]
hmm, let me check @rayandrews

**Comment by deryrahman** [comment]
case closed 👌
